import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import type { Metadata } from "next";
import { kanit } from "./fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.className} flex flex-col antialiased h-screen w-screen `}
      >
        <NavBar />
        <main className="flex flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
