import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="w-full h-10 bg-teal-400 px-10 flex items-center justify-between">
          <div className="flex items-center gap-12">
            <Link href="/">Home</Link>
            <Link href="/about">About</Link>
          </div>
          <div className="flex items-center gap-12">
            <Link href="/blog">Blog</Link>
            <Link href="/projects">Projects</Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
