import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import CartContextProvider from "@/contexts/CartContext";
import { i18n } from "@/i18n/config";
import type { Metadata } from "next";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Head from "next/head";
import { openSans } from "../../fonts/fonts";
import "./globals.css";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const messages = await getMessages();

  return (
    <html>
      <body
        className={`${openSans.className} flex flex-col antialiased min-h-screen w-full`}
      >
        <Head>
          <link
            rel="icon"
            href="/icon?<generated>"
            type="image/png"
            sizes="32x32"
          />
        </Head>

        <NextIntlClientProvider messages={messages}>
          <CartContextProvider>
            <NavBar />
            <main className="flex flex-grow flex-col ">{children}</main>
            <Footer />
          </CartContextProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
