import Footer from "@/components/Footer";
import NavBar from "@/components/NavBar";
import CartContextProvider from "@/contexts/CartContext";
import DictionaryProvider from "@/contexts/DictionaryProvider";
import { i18n, Locale } from "@/i18n-config";
import { getDictionary } from "@/services/get-dictionary";
import type { Metadata } from "next";
import { kanit } from "./fonts/fonts";
import "./globals.css";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  const dictionary = await getDictionary(params.lang);

  return (
    <html lang={params.lang}>
      <body
        className={`${kanit.className} flex flex-col antialiased min-h-screen w-full`}
      >
        {/* <NextIntlClientProvider messages={messages}> */}
        <DictionaryProvider dictionary={dictionary}>
          <CartContextProvider>
            <NavBar />
            <main className="flex flex-grow">{children}</main>
            <Footer />
          </CartContextProvider>
        </DictionaryProvider>
      </body>
    </html>
  );
}
